title: MWNS
brief-intro: Master Wifi Network Solution
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://masterwifinetworksolution.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username: muhammadyusuf1992
github_username:  masterwifinetworksolution
email: myarachma92@gmail.com
youtube_username: masterwifinetworksolution
telegram_username: masterwifinetworksolution
whatsapp_username: 6287764241047
messenger_username: muhammadyusuf1992

description_footer: MWNS adalah website resmi dari channel youtube Master Wifi Network Solution

# comments
duoshuo_shortname: #hygblog
disqus_shortname: masterwifinetworksolution

# statistic analysis
baidu_tongji_id: 
google_analytics_id:  # google id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10

plugins:
  - jekyll-paginate

collections:
  databases:
  docs: