- image: https://down-cvs-id.img.susercontent.com/id-11134207-7ras8-m2m14s4csapr65.webp
  name: TP-Link Archer C54 AC120
  price: Rp291.000
  affiliate_link: https://s.shopee.co.id/4pytE2Q2FB
  category: routers

- image: https://down-cvs-id.img.susercontent.com/id-11134207-7rasm-m2m14s4cmofz2d.webp
  name: TP-Link Archer A6 AC1200
  price: Rp579.000
  affiliate_link: https://s.shopee.co.id/AA0PZzskt3
  category: routers

- image: https://down-aka-sg.img.susercontent.com/id-11134207-7rash-m2m1dkgbskph03.webp
  name: TP-Link Archer C24 AC750
  price: Rp268.000
  affiliate_link: https://s.shopee.co.id/9UkiohLfu9
  category: routers

- image: https://down-aka-sg.img.susercontent.com/id-11134207-7rasi-m2nadbog2ax086.webp
  name: TP-Link Archer AX12 WiFi 6 Router AX1500
  price: Rp525.000
  affiliate_link: https://s.shopee.co.id/8KYlQd269G
  category: routers

- image: https://down-aka-sg.img.susercontent.com/id-11134207-7qul4-lf58uwjr4pwh44.webp
  name: TP-Link WR840N 300Mbps Router Wireless
  price: Rp181.000
  affiliate_link: https://s.shopee.co.id/3AqfHKuW86
  category: routers

- image: https://down-aka-sg.img.susercontent.com/id-11134207-7quky-ljqosg1tjupve2.webp
  name: TP-LINK TL-MR100/MR100+sim 4G LTE Router 300 Mbps Wireless
  price: Rp659.934
  affiliate_link: https://s.shopee.co.id/50IJSnlayQ
  category: routers

- image: 
  name: Produk 2
  price: Rp300.000
  affiliate_link: https://shopee.co.id/produk3
  category: modem

- image: 
  name: Produk 3
  price: Rp300.000
  affiliate_link: https://shopee.co.id/produk3
  category: antena
